import { strict as assert } from "node:assert";
import { test } from "node:test";
import { renderWorkbench } from "../webview";

test("renders project browser and preview form controls", () => {
  const html = renderWorkbench({ cspSource: "vscode-resource:" } as never, "test-nonce");

  assert.match(html, /id="ontology-sources|id="sources/);
  assert.match(html, /id="symbol-groups"/);
  assert.match(html, /id="semantic-search-form"/);
  assert.match(html, /id="semantic-search-kind"/);
  assert.match(html, /type: "semantic-search"/);
  assert.match(html, /type: "semantic-describe"/);
  assert.match(html, /id="semantic-search-results"/);
  assert.match(html, /id="phase4-workbench"/);
  assert.match(html, /id="phase4-refresh"/);
  assert.match(html, /id="reasoning-status"/);
  assert.match(html, /id="shacl-status"/);
  assert.match(html, /Refresh reasoning and validation/);
  assert.match(html, /renderReasoning/);
  assert.match(html, /renderShaclValidation/);
  assert.match(html, /renderShaclShapes/);
  assert.match(html, /preferredSymbolLabel/);
  assert.match(html, /renderProposalImpact/);
  assert.match(html, /type: "phase4-refresh"/);
  assert.match(html, /id="external-workbench"/);
  assert.match(html, /id="external-refresh"/);
  assert.match(html, /id="external-search-form"/);
  assert.match(html, /type: "external-refresh"/);
  assert.match(html, /type: "external-browse"/);
  assert.match(html, /Previous page/);
  assert.match(html, /Next page/);
  assert.match(html, /Back to curated modules/);
  assert.match(html, /overflow-y:\s*auto/);
  assert.match(html, /externalBrowseRequest/);
  assert.match(html, /type: "external-search"/);
  assert.match(html, /Load more results/);
  assert.match(html, /scoreBreakdown/);
  assert.match(html, /Matched by/);
  assert.match(html, /showing .* of/);
  assert.match(html, /Prepare external reuse/);
  assert.match(html, /Prepare local subclass/);
  assert.match(html, /Inspect dependencies/);
  assert.doesNotMatch(html, /readFileSync|parse.*turtle|RDF\.DataFactory|writeFile/);
  assert.match(html, /renderSemanticDescriptor/);
  assert.match(html, /semantic\.definitions/);
  assert.match(html, /Definition/);
  assert.match(html, /formatSearchReason/);
  assert.match(html, /Technical details/);
  assert.match(html, /id="entity-search"/);
  assert.match(html, /Search results are for inspection/);
  assert.doesNotMatch(html, /data-search-picker/);
  assert.doesNotMatch(html, /<button[^>]*>Find /);
  assert.match(html, /type: "resolve-edit-entities"/);
  assert.doesNotMatch(html, /assignSearchResult/);
  assert.doesNotMatch(html, /type: "resolve-entity"/);
  assert.doesNotMatch(html, /type="url"/);
  assert.match(html, /Outgoing properties/);
  assert.match(html, /Incoming relationships/);
  assert.match(html, /formatRelationshipValue/);
  assert.match(html, /id="proposal-form"/);
  assert.match(html, /id="preview-submit" type="button"/);
  assert.match(html, /Stage change/);
  assert.match(html, /Stage deletion/);
  assert.match(html, /id="edit-status"/);
  assert.match(html, /id="edit-kind"/);
  assert.match(html, /create-object-property/);
  assert.match(html, /id="edit-form-placeholder"/);
  assert.match(html, /id="property-fields"/);
  assert.match(html, /id="property-domain-iri"/);
  assert.match(html, /id="property-domain-label"/);
  assert.match(html, /id="property-range-iri"/);
  assert.match(html, /id="property-range-label"/);
  assert.match(html, /id="property-datatype"/);
  assert.match(html, /id="semantic-fields"/);
  assert.match(html, /id="semantic-property-iri"/);
  assert.match(html, /id="semantic-target-iri"/);
  assert.match(html, /id="semantic-definition"/);
  assert.match(html, /id="semantic-existing"/);
  assert.match(html, /id="semantic-replacement"/);
  assert.doesNotMatch(html, /id="semantic-value-iri"/);
  assert.doesNotMatch(html, /id="semantic-annotation-value-kind"/);
  assert.doesNotMatch(html, /id="semantic-language"/);
  assert.doesNotMatch(html, /id="semantic-datatype"/);
  assert.match(html, /type: semanticMode \? "semantic-preview"/);
  assert.match(html, /\[hidden\]\s*\{\s*display:\s*none\s*!important;/);
  assert.match(html, /propertyDatatypeField\.hidden = !datatypeMode/);
  assert.match(html, /id="property-replace"/);
  assert.match(html, /id="individual-fields"/);
  assert.match(html, /id="individual-type-iri"/);
  assert.match(html, /id="individual-type-label"/);
  assert.match(html, /id="assertion-fields"/);
  assert.match(html, /id="assertion-object-iri"/);
  assert.match(html, /id="assertion-object-label"/);
  assert.match(html, /id="assertion-value"/);
  assert.match(html, /id="hierarchy-fields"/);
  assert.match(html, /id="hierarchy-superclass-iri"/);
  assert.match(html, /id="hierarchy-superclass-label"/);
  assert.match(html, /id="label-fields"/);
  assert.match(html, /id="label-replace"/);
  assert.doesNotMatch(html, /id="generate-iri"/);
  assert.match(html, /requestIriGeneration/);
  assert.doesNotMatch(html, /scheduleIriGeneration/);
  assert.match(html, /function submitProposalPreview/);
  assert.match(html, /function submitProposalPreview\(\)[\s\S]*const createAnnotationProperty = editKind\.value === "create-annotation-property"/);
  assert.match(html, /submitProposalPreview\(\);/);
  assert.match(html, /previewSubmit\.addEventListener\("click"/);
  assert.match(html, /type: "generate-iri"/);
  assert.match(html, /id="deletion-form"/);
  assert.match(html, /type: "deletion-dependencies"/);
  assert.match(html, /id="preview-deletion"/);
  assert.match(html, /deleteAction\.id = "delete-symbol"/);
  assert.match(html, /type: "deletion-preview"/);
  assert.match(html, /selectedDependencyKeys/);
  assert.match(html, /checkbox/);
  assert.match(html, /deletion-dependency/);
  assert.match(html, /RequiresExplicitDependencies/);
  assert.match(html, /All dependent statements are selected/);
  assert.match(html, /explicit dependencies required/);
  assert.match(html, /id="staged-changes"/);
  assert.match(html, /id="staged-list"/);
  assert.match(html, /id="cancel-staged-edit"/);
  assert.match(html, /Change staged successfully/);
  assert.doesNotMatch(html, /Preview change/);
  assert.doesNotMatch(html, /Preview deletion/);
  assert.match(html, /Re-preview to return it to the staged list/);
  assert.match(html, /id="preview-all-changes"/);
  assert.match(html, /type: "combined-preview"/);
  assert.match(html, /type: "combined-action"/);
  assert.match(html, /Combined preview is valid and ready for approval/);
  assert.match(html, /The staged list remains available for correction/);
  assert.match(html, /The changes remain staged for correction or another review/);
  assert.match(html, /currentPreview = undefined;[\s\S]*renderStagedList\(\);/);
  assert.match(html, /type: semanticMode \? "semantic-preview" : "proposal-preview"/);
  assert.match(html, /id="preview-validation"/);
  assert.match(html, /id="approve"/);
  assert.match(html, /Approve and apply/);
  assert.match(html, /id="reject"/);
  assert.match(html, /id="open-source"/);
  assert.match(html, /type: "proposal-action"/);
  assert.match(html, /type: "open-source"/);
  assert.match(html, /formatDeletionStatus/);
  assert.match(html, /displayStatementValue/);
  assert.match(html, /function displayIri/);
  const script = html.match(/<script nonce="[^"]+">([\s\S]*)<\/script>/)?.[1];
  assert.ok(script);
  assert.doesNotThrow(() => new Function(script));
});
