import { strict as assert } from "node:assert";
import { test } from "node:test";
import { renderWorkbench } from "../webview";

test("renders project browser and preview form controls", () => {
  const html = renderWorkbench({ cspSource: "vscode-resource:" } as never, "test-nonce");

  assert.match(html, /id="ontology-sources|id="sources/);
  assert.match(html, /id="symbol-groups"/);
  assert.match(html, /id="entity-selector-form"/);
  assert.match(html, /id="entity-selector-kind"/);
  assert.match(html, /type: "resolve-entity"/);
  assert.match(html, /Outgoing properties/);
  assert.match(html, /Incoming relationships/);
  assert.match(html, /formatRelationshipValue/);
  assert.match(html, /id="proposal-form"/);
  assert.match(html, /id="edit-kind"/);
  assert.match(html, /create-object-property/);
  assert.match(html, /id="edit-form-placeholder"/);
  assert.match(html, /id="property-fields"/);
  assert.match(html, /id="property-domain-iri"/);
  assert.match(html, /id="property-range-iri"/);
  assert.match(html, /id="property-datatype"/);
  assert.match(html, /\[hidden\]\s*\{\s*display:\s*none\s*!important;/);
  assert.match(html, /propertyDatatypeField\.hidden = !datatypeMode/);
  assert.match(html, /id="property-replace"/);
  assert.match(html, /id="individual-fields"/);
  assert.match(html, /id="individual-type-iri"/);
  assert.match(html, /id="assertion-fields"/);
  assert.match(html, /id="assertion-object-iri"/);
  assert.match(html, /id="assertion-value"/);
  assert.match(html, /id="hierarchy-fields"/);
  assert.match(html, /id="hierarchy-superclass-iri"/);
  assert.match(html, /id="label-fields"/);
  assert.match(html, /id="label-replace"/);
  assert.match(html, /id="generate-iri"/);
  assert.match(html, /type: "generate-iri"/);
  assert.match(html, /id="deletion-form"/);
  assert.match(html, /type: "deletion-dependencies"/);
  assert.match(html, /id="preview-deletion"/);
  assert.match(html, /deleteAction\.id = "delete-symbol"/);
  assert.match(html, /type: "deletion-preview"/);
  assert.match(html, /selectedDependencyKeys/);
  assert.match(html, /checkbox/);
  assert.match(html, /deletion-dependency/);
  assert.match(html, /RequiresExplicitDependencies/);
  assert.match(html, /All dependent statements are selected/);
  assert.match(html, /explicit dependencies required/);
  assert.match(html, /id="staged-changes"/);
  assert.match(html, /id="staged-list"/);
  assert.match(html, /id="cancel-staged-edit"/);
  assert.match(html, /Change staged successfully/);
  assert.match(html, /Re-preview to return it to the staged list/);
  assert.match(html, /id="preview-all-changes"/);
  assert.match(html, /type: "combined-preview"/);
  assert.match(html, /type: "combined-action"/);
  assert.match(html, /Combined preview is valid and ready for approval/);
  assert.match(html, /The staged list remains available for correction/);
  assert.match(html, /The changes remain staged for correction or another review/);
  assert.match(html, /currentPreview = undefined;[\s\S]*renderStagedList\(\);/);
  assert.match(html, /type: "proposal-preview"/);
  assert.match(html, /id="preview-validation"/);
  assert.match(html, /id="approve"/);
  assert.match(html, /Approve and apply/);
  assert.match(html, /id="reject"/);
  assert.match(html, /id="open-source"/);
  assert.match(html, /type: "proposal-action"/);
  assert.match(html, /type: "open-source"/);
  assert.match(html, /formatDeletionStatus/);
  assert.match(html, /displayStatementValue/);
  assert.match(html, /function displayIri/);
  const script = html.match(/<script nonce="[^"]+">([\s\S]*)<\/script>/)?.[1];
  assert.ok(script);
  assert.doesNotThrow(() => new Function(script));
});
